# ICASSP2025 Dataset Configuration for VAE Training
# Based on RadioMapSeer configuration structure

model:
  embed_dim: 3
  lossconfig:
    disc_start: 50001
    kl_weight: 0.000001
    disc_weight: 0.5
    disc_in_channels: 1
  ddconfig:
    double_z: True
    z_channels: 2
    resolution: [256, 256]  # Updated for ICASSP2025 dataset
    in_channels: 1
    out_ch: 1
    ch: 64
    ch_mult: [ 1,2,4 ]  # num_down = len(ch_mult)-1
    num_res_blocks: 2
    attn_resolutions: [ ]
    dropout: 0.0
  ckpt_path: null  # Start fresh training

data:
  name: radio  # Compatible with RadioMapSeer data loader
  batch_size: 4
  data_root: '/home/cine/Documents/Github/RadioDiff/icassp2025_dataset_arranged'  # ICASSP2025 dataset path

trainer:
  gradient_accumulate_every: 2
  lr: !!float 5e-6
  min_lr: !!float 5e-7
  train_num_steps: 150000
  save_and_sample_every: 5000
  log_freq: 100
  results_folder: '/home/cine/Documents/Github/RadioDiff/results/icassp2025_Vae'
  amp: False
  fp16: False